# ===== JVM & GRADLE PERFORMANCE =====
# -Xmx4g : Ditingkatkan ke 4GB karena GitHub Runner gratisan menyediakan RAM hingga 7GB. Ini krusial agar R8 Full Mode tidak kehabisan RAM.
# -XX:+UseG1GC : G1GC jauh lebih efisien mengosongkan memori fragmen besar pada Gradle 9.6 ketimbang ParallelGC lama.
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1g -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+HeapDumpOnOutOfMemoryError

# ===== PARALLEL BUILD CONFIG =====
# Mengaktifkan configuration cache
org.gradle.configuration-cache=true

# (Opsional tapi disarankan) Mengaktifkan eksekusi cache secara paralel untuk multi-project build
org.gradle.configuration-cache.parallel=true
org.gradle.caching=true

# ===== KOTLIN & ANDROID CONFIG =====
# Mengembalikan ke daemon eksternal terkontrol agar garbage collection compiler Kotlin tidak mengganggu proses utama Gradle
kotlin.compiler.execution.strategy=daemon
kotlin.daemon.jvmargs=-Xmx1g

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# ===== FITUR OPTIMASI TINGKAT LANJUT (AGP 9.3+ & KSP) =====
android.r8.optimizedResourceShrinking=true
android.enableR8.fullMode=true
# Optimasi baru untuk saling berbagi database kompilasi dexing antar modul/task
android.experimental.r8.dex-db-sharing=true
# Memaksa KSP dan Room berjalan dalam mode Inkremental (Hanya memproses file yang berubah)
ksp.incremental=true
# room.incremental=true
# ksp.useKSP2=false
