name: Android Release Build 0

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./coba0

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      # Setup Gradle dengan build-root-directory yang benar
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          # Arahkan root project ke subfolder coba0
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
          # Set false dulu jika ingin workflow_dispatch selalu memperbarui cache
          cache-read-only: false 
          add-job-summary: 'always'

      - name: Build APK (Optimized)
        run: |
          chmod +x ./gradlew

          # Hapus 'clean' agar build cache & configuration cache optimal
          ./gradlew :shared:compileDebugKotlinAndroid \
            --non-interactive \
            --stacktrace \
            --console=plain
        env:
          NO_COLOR: "1"
          ORG_GRADLE_PROJECT_android_native_build_output_ignore_errors: true

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: coba0/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pos-offline-release-signed-apk
          path: |
            ${{ steps.sign_app.outputs.signedReleaseFile }}
            coba0/app/**/*.json
          retention-days: 1
          if-no-files-found: error